# Change these first
owner: lsy223622 # Your GitHub organization or username, where this repository lives
repo: xdncov-mirror-status # The name of this repository

sites:
  - name: Main Site
    url: https://benderblog.github.io/SpiritFlown.html
  - name: Mirror-Ri
    url: https://ncov.raay.xyz/
  - name: Mirror-木生
    url: https://t.lsy223622.com/ncov-xidian-times
  - name: Mirror-Dimole
    url: https://xidian-ncov.dml.ink/
  - name: Mirror-爬
    url: https://ncov.zhouym.tech/
  - name: Mirror-xmgg
    url: https://myxdu.moefactory.com/article/covid19_xdu.html
  - name: Mirror-鱼露
    url: https://ncov.hawa130.com/
  - name: Mirror-没有女朋友跨年的群傻逼
    url: https://x.ksfu.top/
  - name: Mirror-noobwei
    url: https://www.noobwei.xyz/COVID-19.html

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: xdncov-mirror-status.lsy223622.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: xdncov-mirror-status
  introTitle: "西电疫情互助文档整理镜像在线状态"
  introMessage: 西电疫情互助文档整理镜像在线状态
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  customHeadHtml: "<img referrerpolicy="no-referrer-when-downgrade" src="https://analytics.lsy223622.com/matomo.php?idsite=3&amp;rec=1" style="border:0" alt="" />"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
